version: 2
updates:
  - package-ecosystem: "npm"  # Use npm as the package manager
    directory: "/"            # Directory containing the dependencies
    schedule:
      interval: "daily"       # Check updates daily
    commit-message:
      prefix: "chore(deps):"
      include: "scope"        # Add scope to commit messages
    pull-request-branch-name:
      separator: "-"
    rebase-strategy: "auto"   # Automatically rebase pull requests
    labels:                   # Tag pull requests
      - "dependencies"
      - "security"
