version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/"           
    schedule:
      interval: "daily"      
    commit-message:          
      prefix: "chore(deps):"
      include: "scope"
    pull-request-branch-name: 
      separator: "-"
    rebase-strategy: "auto"  
    labels:                 
      - "dependencies"
      - "security"
