version: '3.8'
services:
  app:
    image: liolax/my-devopssec-ca-app:v2
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
    restart: always
    volumes:
      - ./logs:/usr/src/app/logs
