name: Continuous Delivery and Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Pull Docker Image
      - name: Pull Docker Image
        run: |
          docker pull liolax/my-devopssec-ca-app:${{ github.ref_name }}
          docker tag liolax/my-devopssec-ca-app:${{ github.ref_name }} liolax/my-devopssec-ca-app:v2

      # Step 4: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'liolax-devops-app'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          images: 'liolax/my-devopssec-ca-app:${{ github.ref_name }}'
